// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usersettings} from '../models';

export function GetImagePath(arg1:string):Promise<string>;

export function GetLighthouseState():Promise<number>;

export function LoadUserSettings():Promise<usersettings.UserSettings>;

export function Localize(arg1:string):Promise<string>;

export function PrintFromFrontend(arg1:string):Promise<void>;
