// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImagePath(arg1) {
  return window['go']['main']['App']['GetImagePath'](arg1);
}

export function GetLighthouseState() {
  return window['go']['main']['App']['GetLighthouseState']();
}

export function LoadUserSettings() {
  return window['go']['main']['App']['LoadUserSettings']();
}

export function Localize(arg1) {
  return window['go']['main']['App']['Localize'](arg1);
}

export function PrintFromFrontend(arg1) {
  return window['go']['main']['App']['PrintFromFrontend'](arg1);
}
