// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllJsonKeys(arg1, arg2) {
  return window['go']['main']['DataBase']['GetAllJsonKeys'](arg1, arg2);
}

export function GetAllSeverities(arg1, arg2) {
  return window['go']['main']['DataBase']['GetAllSeverities'](arg1, arg2);
}

export function GetDataBaseData(arg1, arg2) {
  return window['go']['main']['DataBase']['GetDataBaseData'](arg1, arg2);
}
