// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {checks} from '../models';
import {database} from '../models';

export function GetData(arg1:Array<checks.Check>):Promise<Array<database.Data>>;
