// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateIssues() {
  return window['go']['main']['DataBase']['CreateIssues']();
}

export function GetAllSeverities(arg1, arg2) {
  return window['go']['main']['DataBase']['GetAllSeverities'](arg1, arg2);
}
