// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {checks} from '../models';

export function GetAllSeverities(arg1:Array<checks.Check>,arg2:Array<number>):Promise<Array<number>>;
