// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {checks} from '../models';
import {scan} from '../models';

export function GetDataBaseData(arg1:Array<checks.Check>):Promise<Array<scan.DataBaseData>>;
