// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeLanguage():Promise<void>;

export function ChangeScanInterval():Promise<void>;

export function ScanNow():Promise<void>;
