// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeLanguage() {
  return window['go']['main']['Tray']['ChangeLanguage']();
}

export function ChangeScanInterval() {
  return window['go']['main']['Tray']['ChangeScanInterval']();
}

export function ScanNow() {
  return window['go']['main']['Tray']['ScanNow']();
}
