// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {checks} from '../models';

export function ChangeLanguage():Promise<void>;

export function ChangeScanInterval():Promise<void>;

export function LogDebug(arg1:string):Promise<void>;

export function LogError(arg1:string):Promise<void>;

export function LogInfo(arg1:string):Promise<void>;

export function ScanNow(arg1:boolean,arg2:string):Promise<Array<checks.Check>>;
