// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {checks} from '../models';

export function ChangeLanguage():Promise<void>;

export function ChangeScanInterval():Promise<void>;

export function LogMessage(arg1:string):Promise<void>;

export function ScanNow():Promise<Array<checks.Check>>;
