// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeLanguage() {
  return window['go']['main']['Tray']['ChangeLanguage']();
}

export function ChangeScanInterval() {
  return window['go']['main']['Tray']['ChangeScanInterval']();
}

export function LogDebug(arg1) {
  return window['go']['main']['Tray']['LogDebug'](arg1);
}

export function LogError(arg1) {
  return window['go']['main']['Tray']['LogError'](arg1);
}

export function LogInfo(arg1) {
  return window['go']['main']['Tray']['LogInfo'](arg1);
}

export function ScanNow(arg1) {
  return window['go']['main']['Tray']['ScanNow'](arg1);
}
